apiVersion: v1
kind: Service
metadata:
  name: producer-api-service
  labels:
    app: producer-api
spec:
  type: ClusterIP 
  #type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    #app: producer-api
    run: producer-api