apiVersion: v1
kind: Service
metadata:
  name: consume-api-service
  labels:
    app: consume-api
spec:
  type: ClusterIP 
  #type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    #app: producer-api
    run: consume-api